### ISSUE TITLE
datepicker-append-to-body implementation

### ISSUE THREAD

**Issue by gmaggio** [zhaber/angular-js-bootstrap-datetimepicker#81]
Is there anyway to implement `datepicker-append-to-body` on this plugin?

Cheers!

**Comment by zhaber** [comment]
Done

**Comment by gmaggio** [comment]
Cool! But I think you forgot the part in the `scope` because it didn't work.

```
          minDate: "=",
          maxDate: "=",
          datepickerAppendToBody: "=", <-- Forgot to add this (line 37)
```

**Comment by zhaber** [comment]
Only attributes that require bi-directional binding are added to the scope. You can run this plunkr and open the source code to see the result. http://plnkr.co/edit/zJOc40?p=preview

**Comment by gmaggio** [comment]
Okay, here's the modified plunkr with only your changes. The datepicker is not appended to the body.

http://plnkr.co/edit/yejSBp?p=preview

And here's one with my suggestion and the append-to-body feature works.

http://plnkr.co/edit/2dByeC?p=preview

**Comment by zhaber** [comment]
In your example the value of the attribute is equal to constant "datepickerAppendToBody", while in the demo (http://plnkr.co/edit/zJOc40?p=preview) it's equal to whatever the attribute is set to (expected behaviour). I also made datepicker-append-to-body an evaluated attribute now to avoid confusion.

**Comment by gmaggio** [comment]
Oh.. Okay.. I didn't see the changes you made. It works now. Tx!
